################################################################################
# Impact of PCV on childhood mortality in 10 PAHO countries                    #
#                                                                              #
#        DATE: May 2019                                                        #
#    CODED BY: Kayoko Shioda (kayoko.shioda@yale.edu)                          #
#     ADVISOR: Dan Weinberger (daniel.weinberger@yale.edu)                     #
################################################################################

#------------------------------------------------------------------------------#
# DESCRIPTION ----
#------------------------------------------------------------------------------#

##### Figure 2 #####
#
# Annual time series for observed and predicted number of pneumonia deaths among
# children aged 2-59 months in ten Latin American and Caribbean countries.
#
# Results are from the final analyses that Kayoko ran in February 2019.
# 
# It uses estimates generated by the "full" model.


##### Figure S2 ######
# 
# Annual time series for observed and predicted number of pneumonia deaths by 
# age group in ten Latin American and Caribbean countries.
#
# Results are from the final analyses that Kayoko ran in February 2019.
# 
# It uses estimates generated by the "full" model.


### Ask Kayoko: check why epi year for certain countries instead of cal year OP
#------------------------------------------------------------------------------#
# Set up ----
#------------------------------------------------------------------------------#

# Function that allows us to include multiple panels in one plot
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

# plotPredAgg()
plotPredAgg <- function(ann_pred_quantiles,  time_points, post_period, #ylim, 
                        outcome_plot, title = NULL, sensitivity_pred_quantiles = NULL, 
                        sensitivity_title = 'Sensitivity Plots', plot_sensitivity = FALSE) {
  
  # Convert intervention date (a date) into the corresponding X-axis value
  if (year_def == 'epi_year') {
    # If year_def is epi_year, then time axis scale is a factor containing epi year names such as "2009/2010"
    month.int <- month(intervention_date)
    year.int  <- year(intervention_date)
    epiyr.int <- ifelse(month.int <=6, year.int - 1, year.int)
    epiyr.start <- paste0(epiyr.int, "-07-01")
    epiyr.end <- paste0(epiyr.int + 1, "-06-30")
    
    decimal.int <- time_length(interval(epiyr.start, intervention_date)) / time_length(interval(epiyr.start, epiyr.end))
    
    year.intervention <-
      which(as.numeric(substr(
        as.character(ann_pred_quantiles$year), 1, 4
      )) == epiyr.int) -1 + 0.5                   # <-------- UPDATED ON MAY 22, 2019
  } else {
    # Otherwise, time axis scale is a number such as 2009; we just need to convert the date to a decimal value
    year.intervention = year(intervention_date)
    last_date = yday(paste0(year.intervention, "-12-31"))
    year.intervention <- year.intervention -1 +0.5 # <-------- UPDATED ON MAY 22, 2019
  }
  #how mny time points in each aggregation period?
  if (year_def == 'epi_year') {
    yrvec <- year(time_points)
    monthvec <- month(time_points)
    epiyrvec = yrvec
    epiyrvec[monthvec <= 6] = yrvec[monthvec <= 6] - 1
    n.months.year <- as.vector(table(epiyrvec))
  } else {
    n.months.year <- as.vector(table(year(time_points)))
  }
  
  
  
  ann_pred_quantiles[,c('2.5%','50%','97.5%','obs')]<-ann_pred_quantiles[,c('2.5%','50%','97.5%','obs')]*12/n.months.year # for partial years, inflate the counts proportional to N months
  
  if (year_def == "cal_year") {
    ann_df<-ann_pred_quantiles[(length(year_int)+1):length(ann_pred_quantiles$year),]
    pred_plot <-ggplot() +
      #geom_polygon(data = data.frame(time = c(post_dates, rev(post_dates)), pred_bound = c(pred_quantiles[which(time_points %in% post_dates), 3], rev(pred_quantiles[which(time_points %in% post_dates), 1]))), aes_string(x = 'time', y = 'pred_bound', color='variable'), alpha = 0.3) +
      geom_ribbon(data=ann_df,
                  aes( x=as.numeric(ann_df$year), 
                       ymin=ann_df$'2.5%', 
                       ymax=ann_df$'97.5%'), alpha=0.5, fill='lightgray')+
      geom_point(data = ann_pred_quantiles, aes_string(x = as.numeric(ann_pred_quantiles$year), y = ann_pred_quantiles$obs)) +
      geom_line(data = ann_df, aes_string(x = as.numeric(ann_df$year), y = ann_df$'50%'), linetype = 'solid', color = 'black') +
      labs(x = 'Year', y = 'No. of deaths') +
      geom_vline(xintercept = year.intervention, linetype='dashed', color='gray')+
      ylim(0, max(ann_df$'97.5%',ann_pred_quantiles$obs)) +
      scale_x_continuous(breaks= pretty_breaks()) +
      ggtitle(title) +
      theme_bw() +
      #scale_x_continuous(breaks = 1:nrow(ann_pred_quantiles), labels = levels(ann_pred_quantiles$year)) +
      theme(axis.line = element_line(colour = "black"),
            axis.text.x = element_text(angle = 0, hjust = 0.5),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank(),
            panel.background = element_blank()) +
      theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
  } else {
    pred_plot <- ggplot() +
      #geom_polygon(data = data.frame(time = c(post_dates, rev(post_dates)), pred_bound = c(pred_quantiles[which(time_points %in% post_dates), 3], rev(pred_quantiles[which(time_points %in% post_dates), 1]))), aes_string(x = 'time', y = 'pred_bound', color='variable'), alpha = 0.3) +
      geom_ribbon(data=ann_pred_quantiles,
                  aes( x=as.numeric(year),
                       ymin=ann_pred_quantiles$'2.5%',
                       ymax=ann_pred_quantiles$'97.5%'), alpha=0.5, fill='lightgray')+
      geom_point(data = ann_pred_quantiles,
                 aes_string(x = as.numeric(ann_pred_quantiles$year), y = ann_pred_quantiles$obs)) +
      geom_line(data = ann_pred_quantiles,
                aes_string(x = as.numeric(ann_pred_quantiles$year), y = ann_pred_quantiles$'50%'),
                linetype = 'solid', color = 'black') +
      labs(x = 'Year', y = 'No. of deaths') +
      geom_vline(xintercept = year.intervention, linetype='dashed', color='gray')+
      ylim(0, max(ann_pred_quantiles$'97.5%')) +
      ggtitle(title) +
      theme_bw() +
      #scale_x_discrete(breaks = 1:nrow(ann_pred_quantiles), labels = levels(ann_pred_quantiles$year)) +
      #scale_x_discrete(ann_pred_quantiles$year) +
      theme(axis.line = element_line(colour = "black"),
            axis.text.x = element_text(angle = 0, hjust = 0.5),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank(),
            panel.background = element_blank()) +
      theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
    pred_plot <- pred_plot + scale_x_continuous(breaks=seq(1,length(as.character(ann_pred_quantiles$year)),3), labels=function(breaks) {
      as.character(ann_pred_quantiles$year[breaks])
    })
  }
  return(pred_plot)
}


create_agg_counts <- function(model,df,time_points,intervention_date){
  y<-df$J12_J18_prim#[df$monthdate>=intervention_date]
  y.pred<-model$y.pred
  y.fitted<-model$y_fitted[,1:length(y)]
  # Create time series plot by age group
  year<-year(time_points)
  year_int <- year(time_points_int)
  pred.sum.year.post<-apply(y.fitted,1, function(x) aggregate(x, by=list('year'=year), FUN=sum))
  pred.sum.year.post<-sapply(pred.sum.year.post,function(x) x[,2])
  y.agg<-aggregate(y, by=list('year'=year), FUN=sum)
  pred.yr.sum.q<- as.data.frame(t(apply(pred.sum.year.post,1,quantile, probs=c(0.025,0.5,0.975))))
  names(pred.yr.sum.q)<-c('2.5%','50%','97.5%')
  pred.yr.sum.q$obs <-y.agg[,2]
  pred.yr.sum.q$year <- unique(year)
  return(pred.yr.sum.q)
}

# Set the working directory
#setwd('~/Documents/paho-adult-mortality-pcvs/')

# Call functions
# source('synthetic_control_functions.R', local = FALSE)
library(lubridate)
library(ggplot2)
library(scales)
library(dplyr)

# Create a list of countries
abbr_country <- c()
list_country <- data.frame(abbr = c("AR","BR","COL","CH","MX"),
                           country = c("Argentina", "Brazil", "Chile","Colombia","Mexico"))
list_agegroups<-c("5-19y","20-39y","40-64y","65-79y","80+y")


#------------------------------------------------------------------------------#
# Yearly time series for obs vs. counter factual pneumo deaths 
# By country ----
#------------------------------------------------------------------------------#

##### Argentina #####
## load dataset
a2 <- readRDS("./Data/PAHO_adults_ICD10reformatted_subchapters.rds") %>%
  filter(country=='AR' & !is.na(agec) & monthdate>='2005-01-01') %>% 
  dplyr::select(-country)
ds.age.spl<-split(a2, a2$agec)
intervention_date=as.Date("2012-01-01")
post_period=c(as.Date("2012-02-01"), as.Date('2012-12-01'))
time_points<-a2$monthdate[a2$agec=="3"]
time_points_int<-a2$monthdate[a2$agec=="3"&a2$monthdate<intervention_date]
year_int <- unique(year(time_points_int))
# Load .rds file
#load("./Results/SC_ridge_noAR1_nonsmoothed.RData")
mod1 <- readRDS("~/Desktop/Kayoko/Results/SC_ridge_AR_nooffset.RDS")

ann_pred_quantiles <- list()
for(i in 1:length(ds.age.spl)){
  print(i)
  model <- mod1[[i]]
  df<-ds.age.spl[[i]]
  ann_pred_quantiles[[i]]<-create_agg_counts(model,df,time_points,intervention_date)
}

# Create empty objects to store results
abbr_country <- c()
title <- c()
plotres <- list()
year_def   <-'cal_year'  

# Create a list of figures
for (i in 1:length(ann_pred_quantiles)) {
  # Create a title 
  #abbr_country[i] <- unlist(strsplit(names(a$results$impact$full$ann_pred_quantiles)[i], " "))[1]
  title[i] <- paste(as.character(list_country$country[1]),
                    list_agegroups[i], sep=" ")
  
  # Define intervention_date
  intervention_date <- post_period[1]
  
  # Create a list of figures
  plotres[[i]] <- plotPredAgg(ann_pred_quantiles = ann_pred_quantiles[[i]], 
                              time_points = time_points,
                              post_period = post_period,
                              #outcome_plot = a$input$outcome_plot[, i],
                              title = title[i])
}
saveRDS(ann_pred_quantiles,"./Results/pred_quantiles_AR_SC_ridge.RDS")
# Save in a new list for later use
ar <- plotres


##### Brazil #####
## load dataset
a2 <- readRDS("./Data/PAHO_adults_ICD10reformatted_subchapters.rds") %>%
  filter(country=='BR' & !is.na(agec) & monthdate>='2005-01-01' & agec %in% c(3,4,5,6,7)) %>% 
  dplyr::select(-country)
ds.age.spl<-split(a2, a2$agec)
intervention_date=as.Date("2010-03-01")
post_period=c(as.Date("2010-04-01"), as.Date('2011-03-01'))
time_points<-a2$monthdate[a2$agec=="3"]
time_points_int<-a2$monthdate[a2$agec=="3"&a2$monthdate<intervention_date]
year_int <- c("2005","2006","2007","2008","2009")# unique(year(time_points_int))
# Load .rds file
mod1 <- readRDS("~/Desktop/Kayoko/Results/SC_ridge_BR_nooffset.RDS")
#load("./Results/SC_Ridge_BR_v1.RData")

ann_pred_quantiles <- list()
for(i in 1:length(ds.age.spl)){
  print(i)
  model <- mod1[[i]]
  df<-ds.age.spl[[i]]
  ann_pred_quantiles[[i]]<-create_agg_counts(model,df,time_points,intervention_date)
  ann_pred_quantiles[[i]]<-ann_pred_quantiles[[i]][1:(nrow(ann_pred_quantiles[[i]])-1),]
}
## Check with Kayoko

# Create empty objects to store results
abbr_country <- c()
title <- c()
plotres <- list()
# Create a list of figures
for (i in 1:length(ann_pred_quantiles)) {
  # Create a title 
  #abbr_country[i] <- unlist(strsplit(names(a$results$impact$full$ann_pred_quantiles)[i], " "))[1]
  title[i] <- paste(as.character(list_country$country[2]),
                    list_agegroups[i], sep=" ")
  
  # Define intervention_date
  intervention_date <- post_period[1]
  
  # Create a list of figures
  plotres[[i]] <- plotPredAgg(ann_pred_quantiles = ann_pred_quantiles[[i]], 
                              time_points = time_points,
                              post_period = post_period,
                              #outcome_plot = a$input$outcome_plot[, i],
                              title = title[i])
}
saveRDS(ann_pred_quantiles,"./Results/pred_quantiles_BR_SC_ridge.RDS")

# Save in a new list for later use
br <- plotres


##### Chile #####
## load dataset
a2 <- readRDS("./Data/PAHO_adults_ICD10reformatted_subchapters.rds") %>%
  filter(country=='CH' & !is.na(agec) & monthdate>='2005-01-01' & agec %in% c(3,4,5,6,7)) %>% 
  dplyr::select(-country)
ds.age.spl<-split(a2, a2$agec)
intervention_date=as.Date("2011-01-01")
post_period=c(as.Date("2011-02-01"), as.Date('2012-01-01'))
time_points<-a2$monthdate[a2$agec=="3"]
time_points_int<-a2$monthdate[a2$agec=="3"&a2$monthdate<intervention_date]
year_int <- unique(year(time_points_int))
# Load .rds file
mod1 <- readRDS("~/Desktop/Kayoko/Results/SC_ridge_CH_nooffset.RDS")
#load("./Results/SC_Ridge_CH_v1.RData")

ann_pred_quantiles <- list()
for(i in 1:length(ds.age.spl)){
  print(i)
  model <- mod1[[i]]
  df<-ds.age.spl[[i]]
  ann_pred_quantiles[[i]]<-create_agg_counts(model,df,time_points,intervention_date)
}

# Create empty objects to store results
abbr_country <- c()
title <- c()
plotres <- list()
# Create a list of figures
for (i in 1:length(ann_pred_quantiles)) {
  # Create a title 
  #abbr_country[i] <- unlist(strsplit(names(a$results$impact$full$ann_pred_quantiles)[i], " "))[1]
  title[i] <- paste(as.character(list_country$country[3]),
                    list_agegroups[i], sep=" ")
  
  # Define intervention_date
  intervention_date <- post_period[1]
  
  # Create a list of figures
  plotres[[i]] <- plotPredAgg(ann_pred_quantiles = ann_pred_quantiles[[i]], 
                              time_points = time_points,
                              post_period = post_period,
                              #outcome_plot = a$input$outcome_plot[, i],
                              title = title[i])
}
# Save in a new list for later use
saveRDS(ann_pred_quantiles,"./Results/pred_quantiles_CH_SC_ridge.RDS")
ch <- plotres


##### COLOMBIA #####
## load dataset
a2 <- readRDS("./Data/PAHO_adults_ICD10reformatted_subchapters.rds") %>%
  filter(country=='COL' & !is.na(agec) & monthdate>='2005-01-01') %>% 
  dplyr::select(-country)
ds.age.spl<-split(a2, a2$agec)
intervention_date=as.Date("2011-01-01")
post_period=c(as.Date("2011-02-01"), as.Date('2012-01-01'))
time_points<-a2$monthdate[a2$agec=="3"]
time_points_int<-a2$monthdate[a2$agec=="3"&a2$monthdate<intervention_date]
year_int <- unique(year(time_points_int))
# Load .rds file
mod1 <- readRDS("~/Desktop/Kayoko/Results/SC_ridge_COL_nooffset.RDS")
#load("./Results/SC_Ridge_COL_v1.RData")

ann_pred_quantiles <- list()
for(i in 1:length(ds.age.spl)){
  print(i)
  model <- mod1[[i]]
  df<-ds.age.spl[[i]]
  ann_pred_quantiles[[i]]<-create_agg_counts(model,df,time_points,intervention_date)
}

# Create empty objects to store results
abbr_country <- c()
title <- c()
plotres <- list()
# Create a list of figures
for (i in 1:length(ann_pred_quantiles)) {
  # Create a title 
  #abbr_country[i] <- unlist(strsplit(names(a$results$impact$full$ann_pred_quantiles)[i], " "))[1]
  title[i] <- paste(as.character(list_country$country[4]),
                    list_agegroups[i], sep=" ")
  
  # Define intervention_date
  intervention_date <- post_period[1]
  
  # Create a list of figures
  plotres[[i]] <- plotPredAgg(ann_pred_quantiles = ann_pred_quantiles[[i]], 
                              time_points = time_points,
                              post_period = post_period,
                              #outcome_plot = a$input$outcome_plot[, i],
                              title = title[i])
}
# Save in a new list for later use
saveRDS(ann_pred_quantiles,"./Results/pred_quantiles_COL_SC_ridge.RDS")
co <- plotres


##### Mexico #####
## load dataset
a2 <- readRDS("./Data/PAHO_adults_ICD10reformatted_subchapters.rds") %>%
  filter(country=='MX' & !is.na(agec) & monthdate>='1999-01-01') %>% 
  dplyr::select(-country)
ds.age.spl<-split(a2, a2$agec)
intervention_date=as.Date("2008-01-01")
post_period=c(as.Date("2008-02-01"), as.Date('2009-01-01'))
time_points<-a2$monthdate[a2$agec=="3"]
time_points_int<-a2$monthdate[a2$agec=="3"&a2$monthdate<intervention_date]
year_int <- unique(year(time_points_int))
# Load .rds file
mod1 <- readRDS("~/Desktop/Kayoko/Results/SC_ridge_MX_nooffset.RDS")
#load("~/Desktop/Kayoko/Results/SC_ridge_MX.RDS")

ann_pred_quantiles <- list()
for(i in 1:length(ds.age.spl)){
  print(i)
  model <- mod1[[i]]
  df<-ds.age.spl[[i]]
  ann_pred_quantiles[[i]]<-create_agg_counts(model,df,time_points,intervention_date)
}

# Create empty objects to store results
abbr_country <- c()
title <- c()
plotres <- list()
# Create a list of figures
for (i in 1:length(ann_pred_quantiles)) {
  # Create a title 
  #abbr_country[i] <- unlist(strsplit(names(a$results$impact$full$ann_pred_quantiles)[i], " "))[1]
  title[i] <- paste(as.character(list_country$country[5]),
                    list_agegroups[i], sep=" ")
  
  # Define intervention_date
  intervention_date <- post_period[1]
  
  # Create a list of figures
  plotres[[i]] <- plotPredAgg(ann_pred_quantiles = ann_pred_quantiles[[i]], 
                              time_points = time_points,
                              post_period = post_period,
                              #outcome_plot = a$input$outcome_plot[, i],
                              title = title[i])
}
# Save in a new list for later use
saveRDS(ann_pred_quantiles,"./Results/pred_quantiles_MX_SC_ridge.RDS")
mx <- plotres


#------------------------------------------------------------------------------#
# Yearly time series for obs vs. counter factual pneumo deaths 
# By age group ----
#------------------------------------------------------------------------------#

##### FIGURE 2 (5-19y) #####

setwd("./Figures/")
pdf("FigSC_ridge_5_19y.pdf", width = 9, height = 10)
multiplot(ar[[1]], co[[1]],br[[1]], ch[[1]], mx[[1]], 
          cols=2)
dev.off()

##### FIGURE S2-# (20-39y) #####
pdf("FigSC_ridge_2_20_39y.pdf", width = 9, height = 10)
multiplot(ar[[2]], co[[2]],br[[2]], ch[[2]], mx[[2]], 
          cols=2)
dev.off()

##### FIGURE S2-A (40-64y) #####
pdf("FigSC_ridge_2_40_64y.pdf", width = 9, height = 10)
multiplot(ar[[3]], co[[3]],br[[3]], ch[[3]], mx[[3]],
          cols=2)
dev.off()

##### FIGURE S2-B (65-79y) #####
pdf("FigSC_ridge_65_79y.pdf", width = 9, height = 8)
multiplot(ar[[4]], co[[4]],br[[4]], ch[[4]], mx[[4]], 
          cols=2)
dev.off()

##### FIGURE S2-C (80+y) #####
pdf("FigSC_ridge_80+y.pdf", width = 9, height = 10)
print(multiplot(ar[[5]], co[[5]],br[[5]], ch[[5]], mx[[5]], 
                cols=2))
dev.off()

